services:
    mundophpbb.stopbadbots.listener:
        class: mundophpbb\stopbadbots\event\main_listener
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@language'
            - '@cache.driver' # Corrigido: substitui %core.table_prefix% por @cache.driver
            - '%core.table_prefix%' # Adicionado para corresponder ao construtor
            - '@log'
            - '%core.root_path%' # Adicionado para corresponder ao construtor
        tags:
            - { name: event.listener }

    mundophpbb.stopbadbots.acp_controller:
        class: mundophpbb\stopbadbots\controller\acp_controller
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@template'
            - '@language'
            - '@request'
            - '@user'
            - '%core.table_prefix%'
            - '%core.php_ext%'
            - '@log'
            - '@pagination'
            - '@files.upload'
            - '@mundophpbb.stopbadbots.cron'
            - '@cache.driver'
            - '%core.root_path%'
        tags:
            - { name: acp_controller }

    mundophpbb.stopbadbots.lang_listener:
        class: mundophpbb\stopbadbots\event\lang_listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }

    mundophpbb.stopbadbots.cron:
        class: mundophpbb\stopbadbots\cron\cron_task
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@cache.driver'
            - '%core.table_prefix%'
            - '@log'
        tags:
            - { name: cron.task }